Models/Car.cs
namespace IntegerWebApp.Models
{
    public class Car
    {
        
        public int IdRegistrasi { get; set; }
        public string Type { get; set; }
        public string Brand { get; set; }
        public string Varian { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace IntegerWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Student.cs
namespace IntegerWebApp.Models
{
    public class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }

    }
}

Controllers/CarController.cs
using IntegerWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace IntegerWebApp.Controllers
{
    public class CarController : Controller
    {
        public IActionResult Index()
        {

            /*   var cars = new List<Car>();

               cars.Add(new Car()
               {
                   IdRegistrasi = 1,
                   Type = "Sport",
                   Brand = "Mustang",
                   Varian="RedCandy"

               });


               cars.Add(new Car()
               {
                   IdRegistrasi = 2,
                   Type = "MPV",
                   Brand = "Avanza",
                   Varian = "Silver"

               });


               cars.Add(new Car()
               {
                   IdRegistrasi = 3,
                   Type = "SUV",
                   Brand = "Pajero Sport Dakar",
                   Varian = "Black Mamba"

               });
               //ViewBag.Cars = cars;
               */

               var cars = new Car[]
               {
                   new Car {IdRegistrasi=0001, Type="Sedan",Brand="Toyota",Varian="FT86"},
                   new Car {IdRegistrasi=0002, Type="SUV",Brand="Toyota",Varian="RAV4"},
                   new Car {IdRegistrasi=0003, Type="Sedan",Brand="Honda",Varian="Accord"},
                   new Car {IdRegistrasi=0004, Type="SUV",Brand="Honda",Varian="CRV"},
                   new Car {IdRegistrasi=0005, Type="Sedan",Brand="Honda",Varian="City"},
               };
            ViewBag.Cars = cars;
           // var cari = cars.Single(x=> x.IdRegistrasi==2);
         
            

            
            var soal1 = cars.Where(x => x.Brand == "Honda").FirstOrDefault();
            ViewBag.satu = new List<Car>() { soal1 };


            var soal2 = cars.Where(x => (x.Brand == "Honda" && x.Type == "Sedan"));
            ViewBag.dua = soal2;

            
            var soal3 = cars.Where(x => (x.Brand == "Honda" && x.Varian == "City")).FirstOrDefault();
            ViewBag.tiga = new List<Car>() { soal3 };

            
            var soal4 = cars.Where(x => (x.Brand == "Toyota"));
            ViewBag.empat = soal4;


            var soal5 = cars.Where(x => x.Varian == "City");
            ViewBag.lima = soal5;

            //soal6
            var soal6 = cars.Where(x => x.Brand == "Honda");
            ViewBag.enam = soal6;

            return View();
        }
    }
}

Controllers/HomeController.cs
using IntegerWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace IntegerWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using IntegerWebApp.Models;
using System.Net;
using System.Xml.Linq;

namespace IntegerWebApp.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Index()
        {

            var student = new List<Student>();
            student.Add(new Student()

            {
                Id = 1,
                Name = "ACHMAD FAUZI",
                Address = "CIANJUR",
                PhoneNumber = "1234567890"
            });

            student.Add(new Student()
            {
                Id = 2,
                Name = "HELMI TRIS EDYAN",
                Address = "BANJAR",
                PhoneNumber = "234556789"
            });

            return View(student);
        }
    }
}

Views/Car/Index.cshtml
@model List<IntegerWebApp.Models.Car>
   
    <div class=" card show p-2">
        <h1>Soal 1</h1>
        <table class="table">
        <thead>
            <tr>
                <th>Id Registrasi</th>
                <th>Type</th>
                <th>Brand</th>
                <th>Varian</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.Satu)
            {
                <tr>
                    <td>@item.IdRegistrasi</td>
                    <td>@item.Type</td>
                    <td>@item.Brand</td>
                    <td>@item.Varian</td>
                </tr>
            }
        </tbody>
        </table>

        <table class="Table">
            <h2>Soal2</h2>
        <thead>
            <tr>
                <th>Id Registrasi</th>
                <th>Type</th>
                <th>Brand</th>
                <th>Varian</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.Dua)
            {
                <tr>
                    <td>@item.IdRegistrasi</td>
                    <td>@item.Type</td>
                    <td>@item.Brand</td>
                    <td>@item.Varian</td>
                </tr>
            }
        </tbody>
        </table>

        
        <table class="Table">
            <h2>Soal3</h2>
        <thead>
            <tr>
                <th>Id Registrasi</th>
                <th>Type</th>
                <th>Brand</th>
                <th>Varian</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.Tiga)
            {
                <tr>
                    <td>@item.IdRegistrasi</td>
                    <td>@item.Type</td>
                    <td>@item.Brand</td>
                    <td>@item.Varian</td>
                </tr>
            }
        </tbody>
        </table>
        

        
        <table class="Table">
            <h2>Soal4</h2>
        <thead>
            <tr>
                <th>Id Registrasi</th>
                <th>Type</th>
                <th>Brand</th>
                <th>Varian</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.Empat)
            {
                <tr>
                    <td>@item.IdRegistrasi</td>
                    <td>@item.Type</td>
                    <td>@item.Brand</td>
                    <td>@item.Varian</td>
                </tr>
            }
        </tbody>
        </table>

        
        <table class="Table">
            <h2>Soal5</h2>
        <thead>
            <tr>
                <th>Id Registrasi</th>
                <th>Type</th>
                <th>Brand</th>
                <th>Varian</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.Lima)
            {
                <tr>
                    <td>@item.IdRegistrasi</td>
                    <td>@item.Type</td>
                    <td>@item.Brand</td>
                    <td>@item.Varian</td>
                </tr>
            }
        </tbody>
        </table>

        
        <table class="Table">
            <h2>Soal6</h2>
        <thead>
            <tr>
                <th>Id Registrasi</th>
                <th>Type</th>
                <th>Brand</th>
                <th>Varian</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.Enam)
            {
                <tr>
                    <td>@item.IdRegistrasi</td>
                    <td>@item.Type</td>
                    <td>@item.Brand</td>
                    <td>@item.Varian</td>
                </tr>
            }
        </tbody>
        </table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h3>Pelatihan Kedua Asp net Core</h3>
    <a href="Student/Index">Buka Student</a> <br/>
    <a asp-controller="Student" asp-action="Index"> Buka Student Via Asp </a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IntegerWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IntegerWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IntegerWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Index">Car</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - IntegerWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Student/Index.cshtml
@model List<Student>;
<h2>Ini dari controller student</h2>

@foreach (var data in Model)
{
    <p>Id : @data.Id</p>
    <p>Name : @data.Name</p>
    <p>Address : @data.Address</p>
    <p>Phone Number : @data.PhoneNumber</p>
    <hr />
}

<a asp-controller="Home" asp-action="Index">Kembali Home</a>